#! /bin/sh

polkit-gnome-authentication-agent-1 &
picom &
sxhkd &
# xrandr -s 1920x1080 -r 144
flashfocus -t 200 --no-flash-fullscreen &
nitrogen --restore
$HOME/Dotfiles/config/polybar/start.sh &


bspc monitor -d Home Web Media Misc Misc

bspc config border_width            2
bspc config window_gap              12
bspc config top_padding             23
bspc config top_monocle_padding     -30

bspc config border_width            3
bspc config normal_border_color     "#ffffff"
bspc config focused_border_color    "#000000"

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_motion_interval 7ms

bspc config external_rules_command "$HOME/Dotfiles/bin/bspwm-external-rules.sh"
bspc rule -a Alacritty state=pseudo_tiled
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Pavucontrol state=floating manage=on layer=above follow=off
bspc rule -a Nitrogen state=floating layer=above
bspc rule -a Blueman-manager state=floating manage=on layer=above follow=off
bspc rule -a Thunar state=floating manage=on layer=normal follow=on
bspc rule -a discord desktop='^3' follow=off
bspc rule -a float state=floating
bspc rule -a Spotify desktop='^3' follow=off