#!/bin/sh

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd

super + x
    bspc node --close

# alternate between the tiled and monocle layout
super + m
    bspc desktop -l next

super + s
    bspc node -t {pseudo_tiled,tiled}

super + shift + f
    bspc node -t fullscreen

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# focus the next/previous node in the current desktop
super + c
    bspc node -f next.local

# focus or send to the given desktop
super + {_,shift + }{1,2,3,q,w}
    bspc {desktop -f,node -d} '^{1-5}'

super + f
    bspc node -t floating

super + i
    dunstify -r 1 "`$SCRIPTS/info.sh`"

super + Return
    alacritty

# super + @space
#   rofi -show combi -display-combi "CMD"
super + @space
    rofi -show run

XF86AudioRaiseVolume
    pamixer -i 2
XF86AudioLowerVolume
    pamixer -d 2
XF86AudioMute
    pamixer -t
XF86AudioPlay
    playerctl play-pause
XF86AudioPrev
    playerctl previous
XF86AudioNext
    playerctl next
Cancel
    playerctl stop
XF86MonBrightnessUp
    xbacklight -inc 10
XF86MonBrightnessDown
    xbacklight -dec 10

Print
    sleep 0.2; \
    scrot -s $HOME/'Y-%m-%d_%H%M%S-$wx$h_scrot.png'

# close and kill
super + shift + x
    $HOME/Dotfiles/config/rofi/scripts/killall.sh

super + shift + c
    $HOME/Dotfiles/config/rofi/scripts/config.sh

super + period
    $HOME/Dotfiles/config/rofi/scripts/emoji-picker.sh
