# https://github.com/spicycode/ze-best-zsh-config

ZSH_CONFIG=$HOME/Dotfiles/config/zsh

source $ZSH_CONFIG/setops.zsh
source $ZSH_CONFIG/exports.zsh
source $ZSH_CONFIG/bindkeys.zsh
source $ZSH_CONFIG/aliases.zsh
source $ZSH_CONFIG/functions.zsh
source $ZSH_CONFIG/plugins/init.zsh
source $ZSH_CONFIG/colors.zsh
source $ZSH_CONFIG/prompt.zsh
