add_newline = true

format = """
[$directory](fg:yellow underline)\
$git_branch\
$git_state\
$git_status\
$character
"""

[character]
success_symbol = "[ »](bold green)"
vicmd_symbol= "[ «](bold blue)"
error_symbol= "[ »](bold red)"

[package]
disabled = true

[directory]
format = "$path"

[git_branch]
format = "$symbol$branch"
symbol = "  "

[git_status]
untracked="  $count"
modified="  $count"
staged="  $count"
renamed=""
behind="  $count"
ahead="  $count"
deleted="  $count"
format = "$all_status$ahead_behind"
