# Override highlighter colors
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=9'
ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[bracket-error]=fg=001
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=fg=012
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=001
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=012,standout
ZSH_HIGHLIGHT_STYLES[alias]=fg=12
ZSH_HIGHLIGHT_STYLES[builtin]=fg=white,bold
ZSH_HIGHLIGHT_STYLES[function]=fg=white,bold
ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold
ZSH_HIGHLIGHT_STYLES[precommand]=fg=white,underline
ZSH_HIGHLIGHT_STYLES[commandseparator]=fg=3
ZSH_HIGHLIGHT_STYLES[autodirectory]=fg=004,underline
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=009
ZSH_HIGHLIGHT_STYLES[path]=fg=004,underline
ZSH_HIGHLIGHT_STYLES[globbing]=fg=002
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=white,underline
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=12
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=12
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=153
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=153
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=003
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=003
ZSH_HIGHLIGHT_STYLES[assign]=none
