[colors.primary]
background = "{background}"
foreground = "{foreground}"

[colors.cursor]
cursor = "{cursor}"
text = "{background}"

[colors.normal]
black = "{color0}"
blue = "{color1}"
cyan = "{color2}"
green = "{color3}"
magenta = "{color4}"
red = "{color5}"
yellow = "{color6}"
white = "{color7}"

[colors.bright]
black = "{color8}"
blue = "{color9}"
cyan = "{color10}"
green = "{color11}"
magenta = "{color12}"
red = "{color13}"
yellow = "{color14}"
white = "{color15}"
